// <auto-generated />
namespace AppointmentManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class booking_rooms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(booking_rooms));
        
        string IMigrationMetadata.Id
        {
            get { return "202112040958343_booking_rooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
